import { DOCUMENT_TYPE_LABELS, type DocumentType } from "@/lib/domain";
import { getEntityProfile } from "@/lib/jurisdictions";
import { renderGoverningDocument } from "./templates/governing";
import {
  renderConsentsToAct,
  renderIncorporationSummary,
  renderShareCertificate,
  renderShareholderRegister,
} from "./templates/registers";
import type { DocumentContext, GeneratedDocument } from "./types";

export type { DocumentContext, GeneratedDocument } from "./types";
export { renderRegistryCertificate, renderFilingReceipt } from "./templates/registry";

function slug(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

function doc(type: DocumentType, ctx: DocumentContext, content: Uint8Array, suffix?: string): GeneratedDocument {
  const title = suffix ? `${DOCUMENT_TYPE_LABELS[type]} — ${suffix}` : DOCUMENT_TYPE_LABELS[type];
  return {
    type,
    title,
    fileName: `${slug(ctx.company.name)}-${slug(title)}.pdf`,
    mimeType: "application/pdf",
    content,
  };
}

/**
 * Render every document in the entity type's formation pack.
 * Share certificates produce one PDF per shareholder.
 */
export async function generateDocumentPack(ctx: DocumentContext): Promise<GeneratedDocument[]> {
  const entity = getEntityProfile(ctx.company.jurisdiction, ctx.company.entityType);
  const ctxWithCerts: DocumentContext = {
    ...ctx,
    shareholders: ctx.shareholders.map((s, i) => ({ ...s, certificateNumber: s.certificateNumber ?? i + 1 })),
  };

  const jobs = entity.documentPack.flatMap((type): Promise<GeneratedDocument>[] => {
    switch (type) {
      case "CERTIFICATE_OF_INCORPORATION":
        return [renderIncorporationSummary(ctxWithCerts).then((c) => doc(type, ctxWithCerts, c, "Summary"))];
      case "CONSTITUTION":
      case "BYLAWS":
      case "OPERATING_AGREEMENT":
      case "ARTICLES_OF_ASSOCIATION":
        return [renderGoverningDocument(type, ctxWithCerts).then((c) => doc(type, ctxWithCerts, c))];
      case "SHAREHOLDER_REGISTER":
        return [renderShareholderRegister(ctxWithCerts).then((c) => doc(type, ctxWithCerts, c))];
      case "SHARE_CERTIFICATE":
        return ctxWithCerts.shareholders.map((s, i) =>
          renderShareCertificate(ctxWithCerts, i).then((c) => doc(type, ctxWithCerts, c, `No. ${s.certificateNumber} ${s.fullName}`)),
        );
      case "CONSENT_TO_ACT":
        return [renderConsentsToAct(ctxWithCerts).then((c) => doc(type, ctxWithCerts, c))];
      case "REGISTRY_FILING":
      case "TAX_ID_CONFIRMATION":
        // Issued by government bodies, not generated by us.
        return [];
    }
  });

  return Promise.all(jobs);
}
export { renderLodgementPack } from "./templates/lodgement-pack";
