import { DOCUMENT_TYPE_LABELS, type DocumentType } from "@/lib/domain";
import { getEntityProfile } from "@/lib/jurisdictions";
import { renderGoverningDocument } from "./templates/governing";
import {
  renderConsentsToAct,
  renderIncorporationSummary,
  renderShareCertificate,
  renderShareholderRegister,
} from "./templates/registers";
import { PENDING_REVIEW_WATERMARK, templateStamp } from "./templates/catalog";
import type { DocumentContext, GeneratedDocument } from "./types";

export type { DocumentContext, GeneratedDocument } from "./types";
export { renderRegistryCertificate, renderFilingReceipt } from "./templates/registry";

function slug(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

function doc(type: DocumentType, ctx: DocumentContext, content: Uint8Array, suffix?: string): GeneratedDocument {
  const title = suffix ? `${DOCUMENT_TYPE_LABELS[type]} — ${suffix}` : DOCUMENT_TYPE_LABELS[type];
  return {
    type,
    title,
    fileName: `${slug(ctx.company.name)}-${slug(title)}.pdf`,
    mimeType: "application/pdf",
    content,
  };
}

/**
 * Render every document in the entity type's formation pack.
 * Share certificates produce one PDF per shareholder.
 */
export interface PackOptions {
  exclude?: DocumentType[];
  /** Approved template keys (`id@fingerprint`). */
  reviewed?: ReadonlySet<string>;
  /** "watermark": mark documents from unreviewed templates as drafts (default); "off": don't. */
  reviewMode?: "watermark" | "off";
}

/** Template stamp + whether to watermark, for a legal document type. */
export function reviewState(type: DocumentType, ctx: DocumentContext, opts: Pick<PackOptions, "reviewed" | "reviewMode">) {
  const stamp = templateStamp(type, ctx);
  if (!stamp) return { template: undefined, watermark: undefined };
  const reviewed = opts.reviewed?.has(`${stamp.id}@${stamp.fingerprint}`) ?? false;
  const watermark = !reviewed && (opts.reviewMode ?? "watermark") === "watermark" ? PENDING_REVIEW_WATERMARK : undefined;
  return { template: { ...stamp, reviewed }, watermark };
}

export async function generateDocumentPack(ctx: DocumentContext, opts: PackOptions = {}): Promise<GeneratedDocument[]> {
  const entity = getEntityProfile(ctx.company.jurisdiction, ctx.company.entityType);
  const ctxWithCerts: DocumentContext = {
    ...ctx,
    shareholders: ctx.shareholders.map((s, i) => ({ ...s, certificateNumber: s.certificateNumber ?? i + 1 })),
  };

  const jobs = entity.documentPack.filter((t) => !opts.exclude?.includes(t)).flatMap((type): Promise<GeneratedDocument>[] => {
    switch (type) {
      case "CERTIFICATE_OF_INCORPORATION":
        return [renderIncorporationSummary(ctxWithCerts).then((c) => doc(type, ctxWithCerts, c, "Summary"))];
      case "CONSTITUTION":
      case "BYLAWS":
      case "OPERATING_AGREEMENT":
      case "ARTICLES_OF_ASSOCIATION": {
        const { template, watermark } = reviewState(type, ctxWithCerts, opts);
        return [renderGoverningDocument(type, ctxWithCerts, { watermark }).then((c) => ({ ...doc(type, ctxWithCerts, c), template }))];
      }
      case "SHAREHOLDER_REGISTER":
        return [renderShareholderRegister(ctxWithCerts).then((c) => doc(type, ctxWithCerts, c))];
      case "SHARE_CERTIFICATE": {
        const { template, watermark } = reviewState(type, ctxWithCerts, opts);
        return ctxWithCerts.shareholders.map((s, i) =>
          renderShareCertificate(ctxWithCerts, i, { watermark }).then((c) => ({ ...doc(type, ctxWithCerts, c, `No. ${s.certificateNumber} ${s.fullName}`), template })),
        );
      }
      case "CONSENT_TO_ACT": {
        const { template, watermark } = reviewState(type, ctxWithCerts, opts);
        return [renderConsentsToAct(ctxWithCerts, { watermark }).then((c) => ({ ...doc(type, ctxWithCerts, c), template }))];
      }
      case "REGISTRY_FILING":
      case "TAX_ID_CONFIRMATION":
        // Issued by government bodies, not generated by us.
        return [];
    }
  });

  return Promise.all(jobs);
}
export { renderLodgementPack } from "./templates/lodgement-pack";
export { renderConsentsToAct, consentStatements, rolePhrase, type ConsentSignature } from "./templates/registers";
export { renderTaxConfirmation, renderTaxWorksheet } from "./templates/tax";
export { TEMPLATES, templateFingerprint, templateFor, PENDING_REVIEW_WATERMARK, type TemplateDefinition } from "./templates/catalog";
export { sampleDocumentContext } from "./sample";
